development: &default
  adapter: postgresql
  encoding: unicode
  database: roban_development
  pool: 5
  username: postgres
  password:
  host: localhost

test:
  <<: *default
  database: roban_test
  adapter: postgresql
